<?php
/**
 * Whitelist de idformulario (tabla formularios) con pantalla v3 lista para permisos.
 * Los textos de formularios siempre se cargan desde la BD; aquí solo enteros.
 *
 * Id 14 obsoleto (usar 70 para inscripción examen web).
 */
declare(strict_types=1);

const FORM_SECRETARIA_MATRICULACION = 1;
const FORM_SECRETARIA_INSCRIPCION_MATERIA = 2;
const FORM_SECRETARIA_LISTADOS_ALUMNOS = 3;
const FORM_SECRETARIA_CALIFICACIONES = 5;
const FORM_SECRETARIA_ASISTENCIAS = 6;
const FORM_SECRETARIA_REGISTROS_PRESISTEMA = 7;
const FORM_SECRETARIA_CERTIFICADOS_ALUMNOS = 8;
const FORM_SECRETARIA_EQUIVALENCIAS = 9;
const FORM_SECRETARIA_MESAS_EXAMEN = 10;
const FORM_SECRETARIA_INSCRIPCION_EXAMENES = 11;
const FORM_SECRETARIA_ACTAS = 12;
const FORM_SECRETARIA_LEGAJOS_PERSONAL = 20;
const FORM_SECRETARIA_LISTADOS_PERSONAL = 22;
const FORM_SECRETARIA_ASIGNAR_DOCENTE_MATERIA = 24;
const FORM_SECRETARIA_PARAMETROS = 33;
const FORM_SECRETARIA_USUARIOS = 40;
const FORM_SECRETARIA_CLAVES_WEB = 41;
const FORM_SECRETARIA_INSCRIPCION_EXAMEN_WEB = 70;
const FORM_SECRETARIA_MATRICULACION_MATERIA_WEB = 71;

/**
 * @return int[]
 */
function formulariosSecretariaV3Ids() {
    return [
        FORM_SECRETARIA_MATRICULACION,
        FORM_SECRETARIA_INSCRIPCION_MATERIA,
        FORM_SECRETARIA_LISTADOS_ALUMNOS,
        FORM_SECRETARIA_CALIFICACIONES,
        FORM_SECRETARIA_ASISTENCIAS,
        FORM_SECRETARIA_REGISTROS_PRESISTEMA,
        FORM_SECRETARIA_CERTIFICADOS_ALUMNOS,
        FORM_SECRETARIA_EQUIVALENCIAS,
        FORM_SECRETARIA_MESAS_EXAMEN,
        FORM_SECRETARIA_INSCRIPCION_EXAMENES,
        FORM_SECRETARIA_ACTAS,
        FORM_SECRETARIA_LEGAJOS_PERSONAL,
        FORM_SECRETARIA_LISTADOS_PERSONAL,
        FORM_SECRETARIA_ASIGNAR_DOCENTE_MATERIA,
        FORM_SECRETARIA_PARAMETROS,
        FORM_SECRETARIA_USUARIOS,
        FORM_SECRETARIA_CLAVES_WEB,
        FORM_SECRETARIA_INSCRIPCION_EXAMEN_WEB,
        FORM_SECRETARIA_MATRICULACION_MATERIA_WEB,
    ];
}
